### ISSUE TITLE
Spigot 1.9

### ISSUE THREAD

**Issue by Keaft** [yariplus/minecraft-nodebb-integration#20]
So I don't have Vault on my server, which I would love to get to solve the problem. However, I'm running 1.9 and Vault isn't quite updated to 1.9. Is it just that I can't use this with 1.9 yet or am I missing something simple?

`[23:17:02] [Server thread/ERROR]: Could not load 'plugins/nodebb-integration-universal-0.7.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Vault
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot.jar:git-Spigot-104c8c8-e43b278]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-104c8c8-e43b278]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot.jar:git-Spigot-104c8c8-e43b278]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot.jar:git-Spigot-104c8c8-e43b278]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
[/code]`

**Comment by da-van** [comment]
Hey Keaft,

I'm running on Spigot 1.9.2 and everything is working great, including Vault. There may not be an official update for Vault for 1.9 yet, but when I updated my server I thought I'd try to see if the latest 1.8 version works ok. It does! :)

Give it a try. If you're still having issues, post back here.

**Comment by yariplus** [comment]
I'm also on 1.9.2 running the 1.8 Vault without issue. That said, there's no real reason to be hard depending on Vault. I might move it to soft depend for the next release.

**Comment by Keaft** [comment]
Vault was installed and all is working.
