### ISSUE TITLE
ASM 5 issues 1.7.10?

### ISSUE THREAD

**Issue by loversama** [yariplus/minecraft-nodebb-integration#23]
Getting a problem relating to ASM 5, running Java 8 and Minecraft 1.7.10 (which I understand this still supports?)

`[16:37:53] [Server thread/ERROR]: Could not load 'plugins/nodebb-integration-universal-0.7.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/radiofreederp/nodebbintegration/MinecraftServer
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[JavaPluginLoader.class:1.7.10-1614.56]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-1614.56]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-1614.56]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:343) [CraftServer.class:1.7.10-1614.56]
    at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
    at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
    at net.minecraft.world.World.<init>(World.java:371) [ahb.class:?]
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: com/radiofreederp/nodebbintegration/MinecraftServer
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:1.7.10-1614.56]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1614.56]
    ... 11 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.radiofreederp.nodebbintegration.MinecraftServer
    at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:512) ~[PluginClassLoader.class:1.7.10-1614.56]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:433) ~[PluginClassLoader.class:1.7.10-1614.56]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.56]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:1.7.10-1614.56]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1614.56]
    ... 11 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
    at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
    at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]
    at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]
    at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:477) ~[PluginClassLoader.class:1.7.10-1614.56]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:433) ~[PluginClassLoader.class:1.7.10-1614.56]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.56]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:1.7.10-1614.56]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1614.56]
    ... 11 more`

The plugin seems pretty amazing, excited to get it working :33

**Comment by yariplus** [comment]
What server jar are you using specifically?

**Comment by loversama** [comment]
I am using FTB Infinity Evolved 2.5.0 along with Thermos, I've not been on Minecraft so wasn't fully aware of the Bukkit situation, I did however follow this:

http://forum.feed-the-beast.com/threads/ftb-infinity-evolved-2-5-0-thermos-guide-bukkit-plugins-for-your-forge-modded-server.152907/

And I am able to get that and Vault running at the moment

**Comment by yariplus** [comment]
Okay. I was able to reproduce on Thermos.

Will fix **Soon**:tm:

**Comment by loversama** [comment]
Thank you very much, really excited about your project, its really awesome :D

**Comment by yariplus** [comment]
Working now on my Thermos test server.

https://github.com/yariplus/minecraft-nodebb-integration/releases/tag/v0.7.3
