### ISSUE TITLE
Sponge 1.10.2 Issues

### ISSUE THREAD

**Issue by phit** [yariplus/minecraft-nodebb-integration#29]
No connection to the forum as far as I can tell and any /nodebb command just throws this NPE
Forge 12.18.2.2099 for Minecraft 1.10.2
spongeforge-1.10.2-2098-5.1.0-BETA-1814

plugins for spongeforge
Nucleus-0.12.1-S5-1.10.2
griefprevention-1.10.2-2.1.0.83
PermissionsEx-build142-Sponge
worldedit-build3610-sponge-mc1.10.2-6.1.4-SNAPSHOT-dist

modpack is the hermitpack on the ftb launcher

```
[15:31:08] [Server thread/INFO] [nucleus/]: Server ran the command: /nodebb help
[15:31:08] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'nodebb help' for source DedicatedServer: null
java.lang.NullPointerException
    at com.radiofreederp.nodebbintegration.commands.CommandNodeBB.help(CommandNodeBB.java:115) ~[CommandNodeBB.class:0.7.3]
    at com.radiofreederp.nodebbintegration.commands.CommandNodeBB.doCommand(CommandNodeBB.java:63) ~[CommandNodeBB.class:0.7.3]
    at com.radiofreederp.nodebbintegration.sponge.commands.CommandNodeBBSponge.execute(CommandNodeBBSponge.java:50) ~[CommandNodeBBSponge.class:0.7.3]
    at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:351) ~[CommandSpec.class:1.10.2-2098-5.1.0-BETA-1814]
    at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2098-5.1.0-BETA-1814]
    at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) [SpongeCommandManager.class:1.10.2-2098-5.1.0-BETA-1814]
    at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:82) [bd.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by yariplus** [comment]
Unable to reproduce.

That line is reading from the config file, maybe try deleting the config so it regenerates?

**Comment by phit** [comment]
Yup, my bad.. forgot "" around the API key.

**Comment by phit** [comment]
activated, but new errors

```
[18:51:13] [pool-2-thread-2/INFO] [nodebbintegration/sponge]: Got Cookie: express.sid=censored; Path=/; Expires=Tue, 01 Nov 2016 22:51:13 GMT; HttpOnly; Secure
[18:51:13] [EventThread/INFO] [nodebbintegration/sponge]: Connected to the forum.
[18:51:13] [Server thread/ERROR] [Sponge/]: The Scheduler tried to run the task nodebbintegration-S-3 owned by Plugin{id=nodebbintegration, name=NodeBBIntegration, version=0.7.3, source=/serverpath/mods/nodebb-integration-universal-0.7.3.jar}, but an error occured.
java.lang.NoSuchMethodError: org.spongepowered.api.plugin.PluginContainer.getVersion()Ljava/lang/String;
    at com.radiofreederp.nodebbintegration.SpongeServer.getPluginList(SpongeServer.java:91) ~[SpongeServer.class:0.7.3]
    at com.radiofreederp.nodebbintegration.tasks.TaskTick.run(TaskTick.java:63) ~[TaskTick.class:0.7.3]
    at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.10.2-2098-5.1.0-BETA-1814]
    at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.10.2-2098-5.1.0-BETA-1814]
    at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) ~[SyncScheduler.class:1.10.2-2098-5.1.0-BETA-1814]
    at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.10.2-2098-5.1.0-BETA-1814]
    at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:160) ~[SchedulerBase.class:1.10.2-2098-5.1.0-BETA-1814]
    at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_101]
    at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:104) [SchedulerBase.class:1.10.2-2098-5.1.0-BETA-1814]
    at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) [SyncScheduler.class:1.10.2-2098-5.1.0-BETA-1814]
    at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.10.2-2098-5.1.0-BETA-1814]
    at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:264) [SpongeMod.class:1.10.2-2098-5.1.0-BETA-1814]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_15_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:130) [EventBus.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:99) [EventBus.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[18:51:21] [pool-2-thread-2/ERROR] [Sponge/sponge]: The Scheduler tried to run the task nodebbintegration-A-11 owned by Plugin{id=nodebbintegration, name=NodeBBIntegration, version=0.7.3, source=/home/moderator/multicraft/servers/server5/mods/nodebb-integration-universal-0.7.3.jar}, but an error occured.
java.lang.NoSuchMethodError: org.spongepowered.api.plugin.PluginContainer.getVersion()Ljava/lang/String;
    at com.radiofreederp.nodebbintegration.SpongeServer.getPluginList(SpongeServer.java:91) ~[SpongeServer.class:0.7.3]
    at com.radiofreederp.nodebbintegration.tasks.TaskTick.run(TaskTick.java:63) ~[TaskTick.class:0.7.3]
    at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.10.2-2098-5.1.0-BETA-1814]
    at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.10.2-2098-5.1.0-BETA-1814]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by yariplus** [comment]
This should work.
https://github.com/yariplus/minecraft-nodebb-integration/releases/tag/v0.7.3.1

**Comment by phit** [comment]
works great, you're the best!

two other small nitpicks, server version is not implemented yet (no big deal, i don't use it anyways)
and motd formatting is broken, for now I replaced toString with toPlain [here](https://github.com/yariplus/minecraft-nodebb-integration/blob/master/sponge/src/main/java/com/radiofreederp/nodebbintegration/SpongeServer.java#L142)

**Comment by yariplus** [comment]
#31
