### ISSUE TITLE
Removing VanishNoPacket breaks the plugin

### ISSUE THREAD

**Issue by comfysquirrel** [yariplus/minecraft-nodebb-integration#6]
If I remove VanishNoPacket, then this error happens, nodebb can't connect, and commands don't work.

```
[23:01:28] [Craft Scheduler Thread - 7/INFO]: [NodeBB-Integration] Success! The socket client was created.
[23:01:28] [EventThread/INFO]: [NodeBB-Integration] Connected to the forum!
[23:01:28] [Server thread/WARN]: [NodeBBIntegration] Task #578 for NodeBBIntegration v0.7.0-beta.3 generated an exception
java.lang.NoClassDefFoundError: org/kitteh/vanish/staticaccess/VanishNotLoadedException
    at com.yaricraft.nodebbintegration.tasks.TaskTick$1.run(TaskTick.java:64) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: org.kitteh.vanish.staticaccess.VanishNotLoadedException
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    ... 8 more
```

**Comment by yariplus** [comment]
Try 
https://github.com/yariplus/bukkit-plugin-nodebb-integration/releases/tag/v0.7.0-beta.4

**Comment by comfysquirrel** [comment]
Yes, that fixed it.
